services:
    # Content Extension
    bigfoot_content.twig.extension.content:
        class: Bigfoot\Bundle\ContentBundle\Twig\Extension\ContentExtension
        arguments:
            - @twig
            - @router
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    # Menu Subscriber
    bigfoot_content.subscriber.menu:
        class: Bigfoot\Bundle\ContentBundle\Subscriber\MenuSubscriber
        arguments: [@security.context]
        tags:
            - { name: kernel.event_subscriber }

    # Template Type
    bigfoot_content.form.type.template:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: admin_template }

    # Page Sidebar Type
    bigfoot_content.form.type.page_sidebar:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\SidebarType
        arguments:
            - %bigfoot_content.templates.sidebar%
        tags:
            - { name: form.type, alias: admin_page_sidebar }

    # Page Block Type
    bigfoot_content.form.type.page_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\BlockType
        arguments:
            - %bigfoot_content.templates.block%
        tags:
            - { name: form.type, alias: admin_page_block }

    # Sidebar Block Type
    bigfoot_content.form.type.sidebar_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\BlockType
        arguments:
            - %bigfoot_content.templates.block%
        tags:
            - { name: form.type, alias: admin_sidebar_block }

    # Page Simple Simple1 Type
    bigfoot_content.form.type.page_simple_simple_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\Simple\Simple1Type
        tags:
            - { name: form.type, alias: admin_page_simple_simple_1 }

    # Page Sidebar Sidebar1 Type
    bigfoot_content.form.type.page_sidebar_sidebar_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\Sidebar\Sidebar1Type
        tags:
            - { name: form.type, alias: admin_page_sidebar_sidebar_1 }

    # Page Sidebar Sidebar2 Type
    bigfoot_content.form.type.page_sidebar_sidebar_2:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\Sidebar\Sidebar2Type
        tags:
            - { name: form.type, alias: admin_page_sidebar_sidebar_2 }

    # Sidebar Vertical Vertical1 Type
    bigfoot_content.form.type.sidebar_vertical_vertical_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\Vertical\Vertical1Type
        tags:
            - { name: form.type, alias: admin_sidebar_vertical_vertical_1 }

    # Sidebar Vertical Vertical2 Type
    bigfoot_content.form.type.sidebar_vertical_vertical_2:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\Vertical\Vertical2Type
        tags:
            - { name: form.type, alias: admin_sidebar_vertical_vertical_2 }

    # Sidebar Vertical Vertical3 Type
    bigfoot_content.form.type.sidebar_vertical_vertical_3:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\Vertical\Vertical3Type
        tags:
            - { name: form.type, alias: admin_sidebar_vertical_vertical_3 }

    # Block Simple Simple1 Type
    bigfoot_content.form.type.block_simple_simple_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\Simple\Simple1Type
        tags:
            - { name: form.type, alias: admin_block_simple_simple_1 }

    # Block Simple Simple2 Type
    bigfoot_content.form.type.block_simple_simple_2:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\Simple\Simple2Type
        tags:
            - { name: form.type, alias: admin_block_simple_simple_2 }

    # Block Simple Simple3 Type
    bigfoot_content.form.type.block_simple_simple_3:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\Simple\Simple3Type
        tags:
            - { name: form.type, alias: admin_block_simple_simple_3 }
