services:
    # Content Extension
    bigfoot_content.twig.extension.content:
        class: Bigfoot\Bundle\ContentBundle\Twig\Extension\ContentExtension
        arguments:
            - @twig
            - @router
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    # Menu Subscriber
    bigfoot_content.subscriber.menu:
        class: Bigfoot\Bundle\ContentBundle\Subscriber\MenuSubscriber
        tags:
            - { name: kernel.event_subscriber }

    # Template Type
    bigfoot_content.form.type.template:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: admin_template }

    # Page Sidebar Type
    bigfoot_content.form.type.page_sidebar:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\SidebarType
        arguments:
            - %bigfoot_content.templates.sidebar%
        tags:
            - { name: form.type, alias: admin_page_sidebar }

    # Page Block Type
    bigfoot_content.form.type.page_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\BlockType
        arguments:
            - %bigfoot_content.templates.block%
        tags:
            - { name: form.type, alias: admin_page_block }

    # Sidebar Block Type
    bigfoot_content.form.type.sidebar_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\BlockType
        arguments:
            - %bigfoot_content.templates.block%
        tags:
            - { name: form.type, alias: admin_sidebar_block }

    # Page TitleDesc TitleDesc1 Type
    bigfoot_content.form.type.page_title_desc_title_desc_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\TitleDesc\TitleDesc1Type
        tags:
            - { name: form.type, alias: admin_page_title_desc_title_desc_1 }

    # Page TitleDescImgSidebar TitleDescImgSidebar1 Type
    bigfoot_content.form.type.page_title_desc_img_sidebar_title_desc_img_sidebar_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\TitleDescImgSidebar\TitleDescImgSidebar1Type
        tags:
            - { name: form.type, alias: admin_page_title_desc_img_sidebar_title_desc_img_sidebar_1 }

    # Page TitleDescSidebar TitleDescSidebar1 Type
    bigfoot_content.form.type.page_title_desc_sidebar_title_desc_sidebar_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\TitleDescSidebar\TitleDescSidebar1Type
        tags:
            - { name: form.type, alias: admin_page_title_desc_sidebar_title_desc_sidebar_1 }

    # Page TitleDescSidebar TitleDescSidebar2 Type
    bigfoot_content.form.type.page_title_desc_sidebar_title_desc_sidebar_2:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\TitleDescSidebar\TitleDescSidebar2Type
        tags:
            - { name: form.type, alias: admin_page_title_desc_sidebar_title_desc_sidebar_2 }

    # Sidebar TitleBlock TitleBlock1 Type
    bigfoot_content.form.type.sidebar_title_block_title_block_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\TitleBlock\TitleBlock1Type
        tags:
            - { name: form.type, alias: admin_sidebar_title_block_title_block_1 }

    # Sidebar TitleDescBlock TitleDescBlock1 Type
    bigfoot_content.form.type.admin_sidebar_title_desc_block_title_desc_block_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\TitleDescBlock\TitleDescBlock1Type
        tags:
            - { name: form.type, alias: admin_sidebar_title_desc_block_title_desc_block_1 }

    # Sidebar TitleDescImgBlock TitleDescImgBlock1 Type
    bigfoot_content.form.type.sidebar_title_desc_img_block_title_desc_img_block_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\TitleDescImgBlock\TitleDescImgBlock1Type
        tags:
            - { name: form.type, alias: admin_sidebar_title_desc_img_block_title_desc_img_block_1 }

    # Block TitleDescImg TitleDescImg1 Type
    bigfoot_content.form.type.block_title_desc_img_title_desc_img_1:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\TitleDescImg\TitleDescImg1Type
        tags:
            - { name: form.type, alias: admin_block_title_desc_img_title_desc_img_1 }

    # Block TitleDescImg TitleDescImg2 Type
    bigfoot_content.form.type.block_title_desc_img_title_desc_img_2:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\TitleDescImg\TitleDescImg2Type
        tags:
            - { name: form.type, alias: admin_block_title_desc_img_title_desc_img_2 }

    # Block TitleDescImg TitleDescImg3 Type
    bigfoot_content.form.type.block_title_desc_img_title_desc_img_3:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\TitleDescImg\TitleDescImg3Type
        tags:
            - { name: form.type, alias: admin_block_title_desc_img_title_desc_img_3 }
