services:
    # Content Extension
    bigfoot_content.twig.extension.content:
        class: Bigfoot\Bundle\ContentBundle\Twig\Extension\ContentExtension
        arguments:
            - @twig
            - @router
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    # Menu Subscriber
    bigfoot_content.subscriber.menu:
        class: Bigfoot\Bundle\ContentBundle\Subscriber\MenuSubscriber
        arguments: [@security.context]
        tags:
            - { name: kernel.event_subscriber }

    # Template Type
    bigfoot_content.form.type.template:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: admin_template }

    # Page Sidebar Type
    bigfoot_content.form.type.page_sidebar:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\SidebarType
        arguments:
            - %bigfoot_content.templates.sidebar%
        tags:
            - { name: form.type, alias: admin_page_sidebar }

    # Page Block Type
    bigfoot_content.form.type.page_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\BlockType
        arguments:
            - %bigfoot_content.templates.block%
        tags:
            - { name: form.type, alias: admin_page_block }

    # Sidebar Block Type
    bigfoot_content.form.type.sidebar_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\BlockType
        arguments:
            - %bigfoot_content.templates.block%
        tags:
            - { name: form.type, alias: admin_sidebar_block }

    # Page Template TitleDesc Type
    bigfoot_content.form.type.page_template_title_desc:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\Template\TitleDescType
        tags:
            - { name: form.type, alias: admin_page_template_title_desc }

    # Page Template TitleDescImgSidebar Type
    bigfoot_content.form.type.page_template_title_desc_img_sidebar:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\Template\TitleDescImgSidebarType
        tags:
            - { name: form.type, alias: admin_page_template_title_desc_img_sidebar }

    # Page Template TitleDescSidebar Type
    bigfoot_content.form.type.page_template_title_desc_sidebar:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\Template\TitleDescSidebarType
        tags:
            - { name: form.type, alias: admin_page_template_title_desc_sidebar }

    # Sidebar Template TitleBlock Type
    bigfoot_content.form.type.sidebar_template_title_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\Template\TitleBlockType
        tags:
            - { name: form.type, alias: admin_sidebar_template_title_block }

    # Sidebar Template TitleDescBlock Type
    bigfoot_content.form.type.sidebar_template_title_desc_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\Template\TitleDescBlockType
        tags:
            - { name: form.type, alias: admin_sidebar_template_title_desc_block }

    # Sidebar Template TitleDescImgBlock Type
    bigfoot_content.form.type.sidebar_template_title_desc_img_block:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\Template\TitleDescImgBlockType
        tags:
            - { name: form.type, alias: admin_sidebar_template_title_desc_img_block }

    # Block Template TitleDescImg Type
    bigfoot_content.form.type.block_template_title_desc_img:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\Template\TitleDescImgType
        tags:
            - { name: form.type, alias: admin_block_template_title_desc_img }