services:
    # Content Extension
    bigfoot_content.twig.extension.content:
        class: Bigfoot\Bundle\ContentBundle\Twig\Extension\ContentExtension
        arguments:
            - @twig
            - @router
            - @doctrine.orm.entity_manager
            - %bigfoot_theme%
        tags:
            - { name: twig.extension }

    # Menu Subscriber
    bigfoot_content.subscriber.menu:
        class: Bigfoot\Bundle\ContentBundle\Subscriber\MenuSubscriber
        arguments: [@security.context]
        tags:
            - { name: kernel.event_subscriber }

    # Template Type
    bigfoot_content.form.type.template:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: admin_template }

    # Page Simple Type
    bigfoot_content.form.type.page_simple:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\SimpleType
        tags:
            - { name: form.type, alias: admin_page_simple }

    # Page TwoColumns Type
    bigfoot_content.form.type.page_two_columns:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Page\TwoColumnsType
        tags:
            - { name: form.type, alias: admin_page_two_columns }

    # Sidebar Simple Type
    bigfoot_content.form.type.sidebar_simple:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Sidebar\SimpleType
        tags:
            - { name: form.type, alias: admin_sidebar_simple }

    # Block Simple Type
    bigfoot_content.form.type.block_simple:
        class: Bigfoot\Bundle\ContentBundle\Form\Type\Block\SimpleType
        tags:
            - { name: form.type, alias: admin_block_simple }
